#mysql
spring.datasource.url=jdbc:mysql://localhost:3306/courses
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=myuser
spring.datasource.password=secret
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true 
#cuidado para nao usar o create e o show-sql true em producao, pois o create vai criar as tabelas toda vez que a aplicacao for iniciada e o show-sql pode expor informacoes sensiveis no log

spring.jpa.hibernate.ddl-auto=create 
#auto=create so pode em ambiente de desenvolvimento, pois ele vai criar as tabelas toda vez que a aplicacao for iniciada, o que pode levar a perda de dados em ambiente de producao. Em producao, geralmente se usa 'update' ou 'validate' para evitar perda de dados.

